services:
  web:
    build: .
    ports:
      - "80:5000"
    depends_on:
      - redis
      - db
  redis:
    image: "redis:alpine"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'very_secure_password'
      MYSQL_DATABASE: med_db
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql